"""0001_initial_schema

Revision ID: 51880363396d
Revises: 
Create Date: 2026-04-21 23:10:42.709986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51880363396d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_secrets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_secrets_name'), 'app_secrets', ['name'], unique=True)
    op.create_table('bot_app_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('redmine_id', sa.BigInteger(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('redmine_id')
    )
    op.create_index(op.f('ix_bot_app_users_login'), 'bot_app_users', ['login'], unique=True)
    op.create_table('bot_heartbeat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_heartbeat_instance_id'), 'bot_heartbeat', ['instance_id'], unique=True)
    op.create_table('bot_issue_journal_cursor',
    sa.Column('issue_id', sa.BigInteger(), nullable=False),
    sa.Column('last_journal_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_table('bot_issue_state',
    sa.Column('user_redmine_id', sa.BigInteger(), nullable=False),
    sa.Column('issue_id', sa.BigInteger(), nullable=False),
    sa.Column('last_status', sa.Text(), nullable=True),
    sa.Column('sent_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_journal_id', sa.Integer(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group_reminder_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('personal_reminder_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_overdue_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_redmine_id', 'issue_id')
    )
    op.create_table('bot_magic_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_bot_magic_tokens_login'), 'bot_magic_tokens', ['login'], unique=False)
    op.create_table('bot_ops_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('crud_action', sa.String(length=32), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_ops_audit_action'), 'bot_ops_audit', ['action'], unique=False)
    op.create_index(op.f('ix_bot_ops_audit_actor_email'), 'bot_ops_audit', ['actor_email'], unique=False)
    op.create_index(op.f('ix_bot_ops_audit_status'), 'bot_ops_audit', ['status'], unique=False)
    op.create_table('bot_sessions',
    sa.Column('session_token', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_token')
    )
    op.create_index(op.f('ix_bot_sessions_user_id'), 'bot_sessions', ['user_id'], unique=False)
    op.create_table('bot_user_leases',
    sa.Column('user_redmine_id', sa.BigInteger(), nullable=False),
    sa.Column('lease_owner_id', sa.UUID(), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_redmine_id')
    )
    op.create_table('cycle_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_settings_key'), 'cycle_settings', ['key'], unique=True)
    op.create_table('matrix_room_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('redmine_id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('verify_code_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrix_room_bindings_user_id'), 'matrix_room_bindings', ['user_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_plain', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_templates_name'), 'notification_templates', ['name'], unique=True)
    op.create_table('notification_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_types_key'), 'notification_types', ['key'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('requested_login', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_requested_login'), 'password_reset_tokens', ['requested_login'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('pending_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_redmine_id', sa.BigInteger(), nullable=False),
    sa.Column('issue_id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_notifications_issue_id'), 'pending_notifications', ['issue_id'], unique=False)
    op.create_index(op.f('ix_pending_notifications_user_redmine_id'), 'pending_notifications', ['user_redmine_id'], unique=False)
    op.create_table('redmine_priorities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('redmine_priority_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redmine_priorities_is_active'), 'redmine_priorities', ['is_active'], unique=False)
    op.create_index(op.f('ix_redmine_priorities_redmine_priority_id'), 'redmine_priorities', ['redmine_priority_id'], unique=True)
    op.create_table('redmine_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('redmine_status_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redmine_statuses_is_active'), 'redmine_statuses', ['is_active'], unique=False)
    op.create_index(op.f('ix_redmine_statuses_redmine_status_id'), 'redmine_statuses', ['redmine_status_id'], unique=True)
    op.create_index(op.f('ix_redmine_statuses_role'), 'redmine_statuses', ['role'], unique=False)
    op.create_table('redmine_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('redmine_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redmine_versions_is_active'), 'redmine_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_redmine_versions_redmine_version_id'), 'redmine_versions', ['redmine_version_id'], unique=True)
    op.create_table('status_room_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_key', sa.String(length=512), nullable=False),
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notify_on_assignment', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_room_routes_status_key'), 'status_room_routes', ['status_key'], unique=True)
    op.create_table('support_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('notify_on_assignment', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('notify', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priorities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('work_hours', sa.String(length=32), nullable=True),
    sa.Column('work_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dnd', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_groups_name'), 'support_groups', ['name'], unique=True)
    op.create_table('version_room_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_key', sa.String(length=512), nullable=False),
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notify_on_assignment', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_room_routes_version_key'), 'version_room_routes', ['version_key'], unique=True)
    op.create_table('bot_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('redmine_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('room', sa.Text(), nullable=False),
    sa.Column('notify', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priorities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('work_hours', sa.String(length=32), nullable=True),
    sa.Column('work_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dnd', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['support_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_users_department'), 'bot_users', ['department'], unique=False)
    op.create_index(op.f('ix_bot_users_display_name'), 'bot_users', ['display_name'], unique=False)
    op.create_index(op.f('ix_bot_users_group_id'), 'bot_users', ['group_id'], unique=False)
    op.create_index(op.f('ix_bot_users_redmine_id'), 'bot_users', ['redmine_id'], unique=True)
    op.create_table('group_version_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('version_key', sa.String(length=512), nullable=False),
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notify_on_assignment', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['support_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'version_key', name='uq_group_version_routes_group_version')
    )
    op.create_index(op.f('ix_group_version_routes_group_id'), 'group_version_routes', ['group_id'], unique=False)
    op.create_table('bot_watcher_cache',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'issue_id')
    )
    op.create_table('pending_digests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.BigInteger(), nullable=False),
    sa.Column('issue_subject', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('journal_notes', sa.Text(), nullable=True),
    sa.Column('status_name', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_digests_user_id'), 'pending_digests', ['user_id'], unique=False)
    op.create_table('user_version_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_user_id', sa.Integer(), nullable=False),
    sa.Column('version_key', sa.String(length=512), nullable=False),
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notify_on_assignment', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bot_user_id'], ['bot_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_user_id', 'version_key', name='uq_user_version_routes_user_version')
    )
    op.create_index(op.f('ix_user_version_routes_bot_user_id'), 'user_version_routes', ['bot_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_version_routes_bot_user_id'), table_name='user_version_routes')
    op.drop_table('user_version_routes')
    op.drop_index(op.f('ix_pending_digests_user_id'), table_name='pending_digests')
    op.drop_table('pending_digests')
    op.drop_table('bot_watcher_cache')
    op.drop_index(op.f('ix_group_version_routes_group_id'), table_name='group_version_routes')
    op.drop_table('group_version_routes')
    op.drop_index(op.f('ix_bot_users_redmine_id'), table_name='bot_users')
    op.drop_index(op.f('ix_bot_users_group_id'), table_name='bot_users')
    op.drop_index(op.f('ix_bot_users_display_name'), table_name='bot_users')
    op.drop_index(op.f('ix_bot_users_department'), table_name='bot_users')
    op.drop_table('bot_users')
    op.drop_index(op.f('ix_version_room_routes_version_key'), table_name='version_room_routes')
    op.drop_table('version_room_routes')
    op.drop_index(op.f('ix_support_groups_name'), table_name='support_groups')
    op.drop_table('support_groups')
    op.drop_index(op.f('ix_status_room_routes_status_key'), table_name='status_room_routes')
    op.drop_table('status_room_routes')
    op.drop_index(op.f('ix_redmine_versions_redmine_version_id'), table_name='redmine_versions')
    op.drop_index(op.f('ix_redmine_versions_is_active'), table_name='redmine_versions')
    op.drop_table('redmine_versions')
    op.drop_index(op.f('ix_redmine_statuses_role'), table_name='redmine_statuses')
    op.drop_index(op.f('ix_redmine_statuses_redmine_status_id'), table_name='redmine_statuses')
    op.drop_index(op.f('ix_redmine_statuses_is_active'), table_name='redmine_statuses')
    op.drop_table('redmine_statuses')
    op.drop_index(op.f('ix_redmine_priorities_redmine_priority_id'), table_name='redmine_priorities')
    op.drop_index(op.f('ix_redmine_priorities_is_active'), table_name='redmine_priorities')
    op.drop_table('redmine_priorities')
    op.drop_index(op.f('ix_pending_notifications_user_redmine_id'), table_name='pending_notifications')
    op.drop_index(op.f('ix_pending_notifications_issue_id'), table_name='pending_notifications')
    op.drop_table('pending_notifications')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_requested_login'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notification_types_key'), table_name='notification_types')
    op.drop_table('notification_types')
    op.drop_index(op.f('ix_notification_templates_name'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_matrix_room_bindings_user_id'), table_name='matrix_room_bindings')
    op.drop_table('matrix_room_bindings')
    op.drop_index(op.f('ix_cycle_settings_key'), table_name='cycle_settings')
    op.drop_table('cycle_settings')
    op.drop_table('bot_user_leases')
    op.drop_index(op.f('ix_bot_sessions_user_id'), table_name='bot_sessions')
    op.drop_table('bot_sessions')
    op.drop_index(op.f('ix_bot_ops_audit_status'), table_name='bot_ops_audit')
    op.drop_index(op.f('ix_bot_ops_audit_actor_email'), table_name='bot_ops_audit')
    op.drop_index(op.f('ix_bot_ops_audit_action'), table_name='bot_ops_audit')
    op.drop_table('bot_ops_audit')
    op.drop_index(op.f('ix_bot_magic_tokens_login'), table_name='bot_magic_tokens')
    op.drop_table('bot_magic_tokens')
    op.drop_table('bot_issue_state')
    op.drop_table('bot_issue_journal_cursor')
    op.drop_index(op.f('ix_bot_heartbeat_instance_id'), table_name='bot_heartbeat')
    op.drop_table('bot_heartbeat')
    op.drop_index(op.f('ix_bot_app_users_login'), table_name='bot_app_users')
    op.drop_table('bot_app_users')
    op.drop_index(op.f('ix_app_secrets_name'), table_name='app_secrets')
    op.drop_table('app_secrets')
    # ### end Alembic commands ###
