"""Единый список экспортов для admin.main.

Вместо from helpers import *, from helpers_ext import * —
явный список всех имён, доступных через _admin().
"""

from __future__ import annotations

# ── Из helpers.py ────────────────────────────────────────────────────────────
from admin.helpers import (
    _ALLOWED_LOGINS_RAW,
    _GENERIC_LOGIN_ERROR,
    _ROOT,
    ADMIN_PORT,
    AUTH_TOKEN_SALT,
    CATALOG_NOTIFY_SECRET,
    CATALOG_VERSIONS_SECRET,
    COOKIE_SECURE,
    CSRF_COOKIE_NAME,
    DASHBOARD_PATH,
    EXCLUDED_PATHS,
    GROUP_UNASSIGNED_DISPLAY,
    GROUP_UNASSIGNED_NAME,
    GROUP_USERS_FILTER_ALL_LABEL,
    LOGIN_PATH,
    RESET_COOLDOWN_SECONDS,
    RESET_TOKEN_TTL_SECONDS,
    SERVICE_TIMEZONE_FALLBACK,
    SERVICE_TIMEZONE_SECRET,
    SESSION_COOKIE_NAME,
    SESSION_TTL_SECONDS,
    SETUP_PATH,
    SHOW_DEV_TOKENS,
    _admin_asset_version,
    _admin_exists_cache,
    _append_audit_file_line,
    _append_ops_to_events_log,
    _client_ip,
    _ensure_csrf,
    _format_datetime_ui,
    _generic_login_error,
    _has_admin,
    _integration_status_cache,
    _jinja_env,
    _login_allowed,
    _login_format_ok,
    _mask_secret,
    _normalize_login,
    _now_utc,
    _parse_catalog_payload,
    _rate_limiter,
    _SimpleRateLimiter,
    _templates_dir,
    _verify_csrf,
    _verify_csrf_json,
    logger,
    templates,
)

# ── Из helpers_ext.py ────────────────────────────────────────────────────────
from admin.helpers_ext import (
    _LOGIN_RE,
    _OPS_FLASH_WITH_DETAIL,
    ADMIN_EXISTS_CACHE_TTL_SECONDS,
    INTEGRATION_STATUS_CACHE_TTL_SECONDS,
    MATRIX_DEFAULT_DEVICE_ID,
    REQUIRED_SECRET_NAMES,
    RUNTIME_STATUS_FILE,
    SESSION_IDLE_TIMEOUT_SECONDS,
    _admin_events_log_path,
    _admin_events_log_scan_bytes,
    _audit_op,
    _build_room_id_async,
    _catalog_key_from_label,
    _dash_events_tail_line_count,
    _dashboard_counts,
    _default_notify_catalog,
    _default_versions_catalog,
    _dimension_preset,
    _get_matrix_client,
    _get_matrix_domain_from_db,
    _group_display_name,
    _group_excluded_from_assignable_lists,
    _groups_assignable,
    _infer_crud_entity_id,
    _integration_status,
    _is_reserved_support_group,
    _load_catalogs,
    _load_priorities_catalog,
    _load_secret_plain,
    _load_statuses_catalog,
    _load_versions_catalog,
    _matrix_bot_mxid,
    _matrix_bot_mxid_from_db,
    _matrix_domain,
    _matrix_domain_from_db,
    _maybe_log_admin_crud,
    _normalize_notify,
    _normalize_notify_catalog,
    _normalize_service_timezone_name,
    _normalize_versions,
    _normalize_versions_catalog,
    _normalized_group_filter_key,
    _ops_flash_message,
    _parse_json_string_list,
    _parse_notify,
    _parse_status_keys_list,
    _parse_work_days,
    _parse_work_hours_range,
    _persist_admin_crud_audit,
    _read_events_log_scan,
    _read_log_tail,
    _room_localpart,
    _runtime_status_from_file,
    _standard_timezone_options,
    _status_preset,
    _sync_matrix_client,
    _timezone_labels,
    _top_timezone_options,
    _truncate_ops_detail,
    _upsert_secret_plain,
    _version_preset,
    effective_bot_timezone_for_admin,
)

# ── Из middleware.py ─────────────────────────────────────────────────────────
from admin.middleware import (
    AuthMiddleware,
    CspSecurityMiddleware,
    _admin_csp_value,
)

# ── Из routes/ops (ре-экспорт для тестов) ────────────────────────────────────
from admin.routes.ops import _restart_in_background

# ── Из внешних модулей ───────────────────────────────────────────────────────
from dash_service_display import service_card_context
from ops.docker_control import get_service_status

# ── Полный __all__ ───────────────────────────────────────────────────────────
__all__ = [
    # helpers.py
    "ADMIN_PORT",
    "AUTH_TOKEN_SALT",
    "CATALOG_NOTIFY_SECRET",
    "CATALOG_VERSIONS_SECRET",
    "COOKIE_SECURE",
    "CSRF_COOKIE_NAME",
    "DASHBOARD_PATH",
    "EXCLUDED_PATHS",
    "GROUP_UNASSIGNED_DISPLAY",
    "GROUP_UNASSIGNED_NAME",
    "GROUP_USERS_FILTER_ALL_LABEL",
    "LOGIN_PATH",
    "RESET_COOLDOWN_SECONDS",
    "RESET_TOKEN_TTL_SECONDS",
    "SERVICE_TIMEZONE_FALLBACK",
    "SERVICE_TIMEZONE_SECRET",
    "SESSION_COOKIE_NAME",
    "SESSION_TTL_SECONDS",
    "SETUP_PATH",
    "SHOW_DEV_TOKENS",
    "_ALLOWED_LOGINS_RAW",
    "_GENERIC_LOGIN_ERROR",
    "_ROOT",
    "_SimpleRateLimiter",
    "_admin_asset_version",
    "_admin_exists_cache",
    "_append_audit_file_line",
    "_append_ops_to_events_log",
    "_client_ip",
    "_ensure_csrf",
    "_format_datetime_ui",
    "_generic_login_error",
    "_has_admin",
    "_integration_status_cache",
    "_jinja_env",
    "_login_allowed",
    "_login_format_ok",
    "_mask_secret",
    "_normalize_login",
    "_now_utc",
    "_parse_catalog_payload",
    "_rate_limiter",
    "_templates_dir",
    "_verify_csrf",
    "_verify_csrf_json",
    "logger",
    "templates",
    # helpers_ext.py
    "ADMIN_EXISTS_CACHE_TTL_SECONDS",
    "INTEGRATION_STATUS_CACHE_TTL_SECONDS",
    "MATRIX_DEFAULT_DEVICE_ID",
    "REQUIRED_SECRET_NAMES",
    "RUNTIME_STATUS_FILE",
    "SESSION_IDLE_TIMEOUT_SECONDS",
    "_LOGIN_RE",
    "_OPS_FLASH_WITH_DETAIL",
    "_admin_events_log_path",
    "_admin_events_log_scan_bytes",
    "_audit_op",
    "_build_room_id_async",
    "_catalog_key_from_label",
    "_dash_events_tail_line_count",
    "_dashboard_counts",
    "_default_notify_catalog",
    "_default_versions_catalog",
    "_get_matrix_client",
    "_get_matrix_domain_from_db",
    "_group_display_name",
    "_group_excluded_from_assignable_lists",
    "_groups_assignable",
    "_infer_crud_entity_id",
    "_integration_status",
    "_is_reserved_support_group",
    "_load_catalogs",
    "_load_statuses_catalog",
    "_load_versions_catalog",
    "_load_priorities_catalog",
    "_load_secret_plain",
    "_matrix_bot_mxid",
    "_matrix_bot_mxid_from_db",
    "_matrix_domain",
    "_matrix_domain_from_db",
    "_maybe_log_admin_crud",
    "_normalize_notify",
    "_normalize_notify_catalog",
    "_normalize_service_timezone_name",
    "effective_bot_timezone_for_admin",
    "_normalize_versions",
    "_normalize_versions_catalog",
    "_normalized_group_filter_key",
    "_dimension_preset",
    "_status_preset",
    "_ops_flash_message",
    "_parse_json_string_list",
    "_parse_notify",
    "_parse_status_keys_list",
    "_parse_work_days",
    "_parse_work_hours_range",
    "_persist_admin_crud_audit",
    "_read_events_log_scan",
    "_read_log_tail",
    "_room_localpart",
    "_runtime_status_from_file",
    "_standard_timezone_options",
    "_sync_matrix_client",
    "_timezone_labels",
    "_top_timezone_options",
    "_truncate_ops_detail",
    "_upsert_secret_plain",
    "_version_preset",
    # middleware.py
    "AuthMiddleware",
    "CspSecurityMiddleware",
    "_admin_csp_value",
    # внешние модули
    "service_card_context",
    "get_service_status",
    # routes/ops (ре-экспорт)
    "_restart_in_background",
]
